// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydszboqpgywpwfqprdqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkc3pib3FwZ3l3cHdmcXByZHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTE5NDksImV4cCI6MjA2NzcyNzk0OX0.S8XAJDl790VUYEtfev7IZ0MU6YEZep7YY_CbG-qNE50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});